# For Minisys only
set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PACKAGE_PIN Y18 [get_ports fpga_clk]
create_clock -period 10 [get_ports fpga_clk]

set_input_delay -clock fpga_clk 2 [get_ports upg_rx_i]
set_output_delay -clock fpga_clk 2 [get_ports upg_tx_o]
set_property PACKAGE_PIN Y19 [get_ports upg_rx_i]
set_property PACKAGE_PIN V18 [get_ports upg_tx_o]

set_input_delay -clock fpga_clk 1 [get_ports {buttons[4]}]
set_input_delay -clock fpga_clk 1 [get_ports {buttons[3]}]
set_input_delay -clock fpga_clk 1 [get_ports {buttons[2]}]
set_input_delay -clock fpga_clk 1 [get_ports {buttons[1]}]
set_input_delay -clock fpga_clk 1 [get_ports {buttons[0]}]
set_property PACKAGE_PIN P5 [get_ports {buttons[4]}]
set_property PACKAGE_PIN P1 [get_ports {buttons[3]}]
set_property PACKAGE_PIN P4 [get_ports {buttons[2]}]
set_property PACKAGE_PIN R1 [get_ports {buttons[1]}]
set_property PACKAGE_PIN P2 [get_ports {buttons[0]}]

set_property PACKAGE_PIN K17 [get_ports {led[23]}]
set_property PACKAGE_PIN L13 [get_ports {led[22]}]
set_property PACKAGE_PIN M13 [get_ports {led[21]}]
set_property PACKAGE_PIN K14 [get_ports {led[20]}]
set_property PACKAGE_PIN K13 [get_ports {led[19]}]
set_property PACKAGE_PIN M20 [get_ports {led[18]}]
set_property PACKAGE_PIN N20 [get_ports {led[17]}]
set_property PACKAGE_PIN N19 [get_ports {led[16]}]
set_property PACKAGE_PIN M17 [get_ports {led[15]}]
set_property PACKAGE_PIN M16 [get_ports {led[14]}]
set_property PACKAGE_PIN M15 [get_ports {led[13]}]
set_property PACKAGE_PIN K16 [get_ports {led[12]}]
set_property PACKAGE_PIN L16 [get_ports {led[11]}]
set_property PACKAGE_PIN L15 [get_ports {led[10]}]
set_property PACKAGE_PIN L14 [get_ports {led[9]}]
set_property PACKAGE_PIN J17 [get_ports {led[8]}]
set_property PACKAGE_PIN F21 [get_ports {led[7]}]
set_property PACKAGE_PIN G22 [get_ports {led[6]}]
set_property PACKAGE_PIN G21 [get_ports {led[5]}]
set_property PACKAGE_PIN D21 [get_ports {led[4]}]
set_property PACKAGE_PIN E21 [get_ports {led[3]}]
set_property PACKAGE_PIN D22 [get_ports {led[2]}]
set_property PACKAGE_PIN E22 [get_ports {led[1]}]
set_property PACKAGE_PIN A21 [get_ports {led[0]}]

set_property PACKAGE_PIN Y9 [get_ports {switches[23]}]
set_property PACKAGE_PIN W9 [get_ports {switches[22]}]
set_property PACKAGE_PIN Y7 [get_ports {switches[21]}]
set_property PACKAGE_PIN Y8 [get_ports {switches[20]}]
set_property PACKAGE_PIN AB8 [get_ports {switches[19]}]
set_property PACKAGE_PIN AA8 [get_ports {switches[18]}]
set_property PACKAGE_PIN V8 [get_ports {switches[17]}]
set_property PACKAGE_PIN V9 [get_ports {switches[16]}]
set_property PACKAGE_PIN AB6 [get_ports {switches[15]}]
set_property PACKAGE_PIN AB7 [get_ports {switches[14]}]
set_property PACKAGE_PIN V7 [get_ports {switches[13]}]
set_property PACKAGE_PIN AA6 [get_ports {switches[12]}]
set_property PACKAGE_PIN Y6 [get_ports {switches[11]}]
set_property PACKAGE_PIN T6 [get_ports {switches[10]}]
set_property PACKAGE_PIN R6 [get_ports {switches[9]}]
set_property PACKAGE_PIN V5 [get_ports {switches[8]}]
set_property PACKAGE_PIN U6 [get_ports {switches[7]}]
set_property PACKAGE_PIN W5 [get_ports {switches[6]}]
set_property PACKAGE_PIN W6 [get_ports {switches[5]}]
set_property PACKAGE_PIN U5 [get_ports {switches[4]}]
set_property PACKAGE_PIN T5 [get_ports {switches[3]}]
set_property PACKAGE_PIN T4 [get_ports {switches[2]}]
set_property PACKAGE_PIN R4 [get_ports {switches[1]}]
set_property PACKAGE_PIN W4 [get_ports {switches[0]}]

set_property PACKAGE_PIN A18 [get_ports {tube_en[7]}]
set_property PACKAGE_PIN A20 [get_ports {tube_en[6]}]
set_property PACKAGE_PIN B20 [get_ports {tube_en[5]}]
set_property PACKAGE_PIN E18 [get_ports {tube_en[4]}]
set_property PACKAGE_PIN F18 [get_ports {tube_en[3]}]
set_property PACKAGE_PIN D19 [get_ports {tube_en[2]}]
set_property PACKAGE_PIN E19 [get_ports {tube_en[1]}]
set_property PACKAGE_PIN C19 [get_ports {tube_en[0]}]

set_property PACKAGE_PIN F15 [get_ports {tube_seg[7]}]
set_property PACKAGE_PIN F13 [get_ports {tube_seg[6]}]
set_property PACKAGE_PIN F14 [get_ports {tube_seg[5]}]
set_property PACKAGE_PIN F16 [get_ports {tube_seg[4]}]
set_property PACKAGE_PIN E17 [get_ports {tube_seg[3]}]
set_property PACKAGE_PIN C14 [get_ports {tube_seg[2]}]
set_property PACKAGE_PIN C15 [get_ports {tube_seg[1]}]
set_property PACKAGE_PIN E13 [get_ports {tube_seg[0]}]

# VGA
set_property PACKAGE_PIN H15 [get_ports {vga_red[3]}]
set_property PACKAGE_PIN J15 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN G18 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_red[0]}]

set_property PACKAGE_PIN H22 [get_ports {vga_green[3]}]
set_property PACKAGE_PIN J22 [get_ports {vga_green[2]}]
set_property PACKAGE_PIN H18 [get_ports {vga_green[1]}]
set_property PACKAGE_PIN H17 [get_ports {vga_green[0]}]

set_property PACKAGE_PIN K22 [get_ports {vga_blue[3]}]
set_property PACKAGE_PIN K21 [get_ports {vga_blue[2]}]
set_property PACKAGE_PIN G20 [get_ports {vga_blue[1]}]
set_property PACKAGE_PIN H20 [get_ports {vga_blue[0]}]

set_property PACKAGE_PIN M21 [get_ports {vga_hsync}]
set_property PACKAGE_PIN L21 [get_ports {vga_vsync}]